name: joistic
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  dio: ^5.6.0
  cloud_firestore: ^5.3.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/